### ISSUE TITLE
Missing dialogue

### ISSUE THREAD

**Issue by GoldAndPurple** [pathologicdialogue/pathologicdialogue.github.io#1]
After the latest updates.
You can see [here](https://github.com/pathologicdialogue/pathologicdialogue.github.io/commit/4610434be83991242a2725eaff4ff9cbba3f751b#diff-ce5a3989f7f9748a8c21a52798cfd6a976943f6549bb3bb4c79f0633bb52c9a4) that a bunch of lines just didn't make it to the new version.
I was searching for P2 Andrey's dialogue specifically, but somebody else might also be lacking.

**Comment by mkounkel** [comment]
Could you give an example?

**Comment by pathologicdialogue** [comment]
Could you give an example?

**Comment by GoldAndPurple** [comment]
Compare the [current version](https://pathologicdialogue.github.io/html2_en/AndreyStamatin.html) and [cached one](https://webcache.googleusercontent.com/search?q=cache:XxPHaKmHyg0J:https://pathologicdialogue.github.io/html2_ru/AndreyStamatin.html).
The beginning of diurnal ending dialogue is not present (newer version starts at "Well, mine was just murdered!" instead) and the discussion about Inquisitor is missing entirely (the one that started with "She has a stump of an imagination.")

**Comment by pathologicdialogue** [comment]
Resolved 81517bc
