### ISSUE TITLE
Additional P1 languages: DE, IT, PL, CZ

### ISSUE THREAD

**Issue by rathologic** [pathologicdialogue/pathologicdialogue.github.io#2]
Hey all, great work so far! The site is missing the German, Italian, Polish, and Czech official translations of Pathologic; I have copies of these and would be happy to send them over if you can support a broader language selection. Maybe a dropdown toolbar to toggle language would be more scaleable than the current layout? The Polish version (and IIRC, maybe the Italian one) was originally fan-made; I'm not sure what your attribution needs are like, but both have been distributed in official capacities (the IPL website and GOG's release of PCHD respectively).

Similarly, it would be nice if the unofficial Chinese (Simplified), Korean, German, Italian, Spanish, and Ukrainian [translations of patho2 ](https://pathomodding.miraheze.org/wiki/Pathologic_2/Translations) could be uploaded alongside the uploaded Brazilian Portuguese translation, provided that their creators are OK with it!

**Comment by pathologicdialogue** [comment]
If you can send me the files, I can add them.
For P1 - do you know if the numbering in main.dat file is identical for all these versions? If so, I would only need that file, or Strings.vfs. In the original version, English and Russian versions were different, but in the PCHD they were the same. If they are different, I will also need Scripts.vfs

I won't go out asking for the permission from the creators of the translations for P2, but if you can get it, I would happily add them in.

**Comment by rathologic** [comment]
https://drive.google.com/drive/folders/1RmE7zmMfvMsuvOUxrQAQ4kp01qqhMtsu

This should contain the relevant files. Turns out I only have a copy of Strings.vfs for the Czech translation, so I can't guarantee its IDs will be readable (although if anything it should match the original RU IDs. If not, you could check if there exists a scripts file from the fanmade [updated version](https://www.farflame.cz/pathologic.htm) of this localization); the Polish translation was patch-based and as such, does not generate any modified script files; I've thrown in Scripts.vfs for the other two.

The Polish version also translates the message on Farkhad's grave, but there aren't any other localizations (as the [English version](https://forum.ice-pick.com/viewtopic.php?f=12&t=4782) provided by Halfgild Wynac is unofficial).

**Comment by rathologic** [comment]
I completely forgot that the original 2006 English localization is also relevant (at least, sought-after by fans) for comparison with the Classic HD release. Attached should be 
the appropriate main.dat file! The numbering is the same inasmuch as this file can be swapped into Classic HD without any problem. Let me know if I can assist further.

[2006.dat.zip](https://github.com/pathologicdialogue/pathologicdialogue.github.io/files/13432911/2006.dat.zip)

**Comment by rathologic** [comment]
just came across [this Portuguese (Brazilian) translation](https://steamcommunity.com/app/384110/discussions/0/3055112595734747852/) for p1.

**Comment by pathologicdialogue** [comment]
Done
